# -*- coding: utf-8 -*-
"""simple-data-automation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui6rDOeA5zNXOhUqquy16WMD_mJE-MtE
"""

import pandas as pd

data = {
    "Produk": [
        "Meja Besi",
        "Kursi Besi",
        "Rak Besi",
        "Meja Besi",
        "Kursi Besi"
    ],
    "Jumlah": [2, 5, 3, 4, 7],
    "Harga": [750000, 350000, 500000, 750000, 350000]
}

df = pd.DataFrame(data)

df["Omzet"] = df["Jumlah"] * df["Harga"]

print(df)

total_transaksi = len(df)
total_produk = df["Jumlah"].sum()
total_omzet = df["Omzet"].sum()

produk_terlaris = (
    df.groupby("Produk")["Jumlah"]
    .sum()
    .idxmax()
)

jumlah_terlaris = (
    df.groupby("Produk")["Jumlah"]
    .sum()
    .max()
)

print("================================")
print("      SALES AUTOMATION REPORT")
print("================================")

print("Total Transaksi :", total_transaksi)
print("Total Produk    :", total_produk, "unit")
print("Total Omzet     : Rp", total_omzet)

print("--------------------------------")

print("Produk Terlaris :", produk_terlaris)
print("Jumlah Terjual  :", jumlah_terlaris, "unit")

print("================================")

laporan = f"""
================================
      SALES AUTOMATION REPORT
================================

Total Transaksi : {total_transaksi}
Total Produk    : {total_produk} unit
Total Omzet     : Rp {total_omzet:,}

--------------------------------

Produk Terlaris : {produk_terlaris}
Jumlah Terjual  : {jumlah_terlaris} unit

================================
"""

with open("report.txt", "w") as file:
    file.write(laporan)

print("Laporan berhasil dibuat!")

ringkasan = pd.DataFrame({
    "Total Transaksi": [total_transaksi],
    "Total Produk": [total_produk],
    "Total Omzet": [total_omzet],
    "Produk Terlaris": [produk_terlaris],
    "Jumlah Terjual Produk Terlaris": [jumlah_terlaris]
})

ringkasan.to_csv("sales_summary.csv", index=False)

print("File sales_summary.csv berhasil dibuat!")

df.to_csv("sales_data.csv", index=False)

print("sales_data.csv berhasil dibuat!")

import pandas as pd

# ==========================================
# SIMPLE DATA AUTOMATION
# ==========================================

# Membuat data penjualan
data = {
    "Produk": [
        "Meja Besi",
        "Kursi Besi",
        "Rak Besi",
        "Meja Besi",
        "Kursi Besi"
    ],
    "Jumlah": [2, 5, 3, 4, 7],
    "Harga": [750000, 350000, 500000, 750000, 350000]
}

df = pd.DataFrame(data)

# Menghitung omzet
df["Omzet"] = df["Jumlah"] * df["Harga"]

# Ringkasan data
total_transaksi = len(df)
total_produk = df["Jumlah"].sum()
total_omzet = df["Omzet"].sum()

# Mencari produk terlaris
penjualan_produk = df.groupby("Produk")["Jumlah"].sum()

produk_terlaris = penjualan_produk.idxmax()
jumlah_terlaris = penjualan_produk.max()

# Membuat laporan
laporan = f"""
================================
      SALES AUTOMATION REPORT
================================

Total Transaksi : {total_transaksi}
Total Produk    : {total_produk} unit
Total Omzet     : Rp {total_omzet:,}

--------------------------------

Produk Terlaris : {produk_terlaris}
Jumlah Terjual  : {jumlah_terlaris} unit

================================
"""

# Menyimpan laporan
with open("report.txt", "w") as file:
    file.write(laporan)

# Menyimpan data hasil analisis
df.to_csv("sales_data.csv", index=False)

ringkasan = pd.DataFrame({
    "Total Transaksi": [total_transaksi],
    "Total Produk": [total_produk],
    "Total Omzet": [total_omzet],
    "Produk Terlaris": [produk_terlaris],
    "Jumlah Terjual Produk Terlaris": [jumlah_terlaris]
})

ringkasan.to_csv("sales_summary.csv", index=False)

print("================================")
print("AUTOMATION SELESAI")
print("================================")
print("File berhasil dibuat:")
print("- sales_data.csv")
print("- sales_summary.csv")
print("- report.txt")